[server]
headless = true         
port = 8501             
enableCORS = false       

[theme]
primaryColor = "#9514FF"   
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#fde8ff" 
textColor = "#9514FF"       
font = "sans serif"         
